name: Upload to infinityfree
on:
  push:
    branches: [ main ]
jobs:
  upload-ftp:
    name: Upload to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get website code
        uses: actions/checkout@v3
        
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpupload.net
          username: epiz_31170569
          password: ${{secrets.passwordftp}}
          protocol: ftps
          port: 21
